apiVersion: v1
kind: Service
metadata:
  name: sigmastream-service
  labels:
    app: sigmastream
spec:
  type: LoadBalancer
  selector:
    app: sigmastream
  ports:
    - name: http
      targetPort: 3000
      port: 8080
